### PR TITLE
Fixes for tf, processROI, and cvtColor errors

### PR DESCRIPTION
**Pull request by j0shcap**
- Tensorflow updated to be compatible with newest version
- Errors with not not returning and using variables with the processROI and drawfromROI are patched.
- CvtColor assertion error when image is empty is patched, only modifies frame if frame exists.

### CODE REVIEW

**Comment by JoshCap20** [comment]
- Tensorflow updated to be compatible with newest version
- Errors with not not returning and using variables with the processROI and drawfromROI are patched.
- CvtColor assertion error when image is empty is patched, only modifies frame if frame exists.

**Comment by j0shcap** [comment]
Added requirements.txt for easier setup in future.

**Comment by zzeitt** [comment]
Hello @JoshCap20 , thank you for your contribution! It's great that you patched this old repository's codes. I will review the code and confirm the merge ASAP.

**Comment by j0shcap** [comment]
Happy to help! This has so many uses -- my favorite is hooking it up to a Roku API and controlling my TV with my hands.

**Comment by zzeitt** [comment]
That's fascinating! My initial thought is using this recognition tool as an engine to control games. I am happy that you found it useful.

**Pull request merged**
